// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cwiczenia5.Data;

#nullable disable

namespace cwiczenia5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("cwiczenia5.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("char");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Component", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "8-core desktop processor",
                            Name = "Ryzen 7 7700X"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "Mid-range gaming GPU",
                            Name = "GeForce RTX 4070"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "DDR5 5600 MHz memory module",
                            Name = "Vengeance 16GB DDR5"
                        });
                });

            modelBuilder.Entity("cwiczenia5.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "CORSAIR",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair Gaming, Inc."
                        });
                });

            modelBuilder.Entity("cwiczenia5.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("cwiczenia5.Entities.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warranty")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Weight")
                        .HasPrecision(5)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PC", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Rig X1",
                            Stock = 10,
                            Warranty = 24,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Pro M2",
                            Stock = 25,
                            Warranty = 12,
                            Weight = 8f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Z3",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 15.2f
                        });
                });

            modelBuilder.Entity("cwiczenia5.Entities.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponent", (string)null);

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 3,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        });
                });

            modelBuilder.Entity("cwiczenia5.Entities.Component", b =>
                {
                    b.HasOne("cwiczenia5.Entities.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cwiczenia5.Entities.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("cwiczenia5.Entities.PcComponent", b =>
                {
                    b.HasOne("cwiczenia5.Entities.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cwiczenia5.Entities.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("cwiczenia5.Entities.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("cwiczenia5.Entities.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("cwiczenia5.Entities.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("cwiczenia5.Entities.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
